version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.10.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run: 'apt-get install wget -y'
      - run: 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      - run: 'sh -c \'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list\''
      - run: 'apt-get update && apt-get install -y google-chrome-stable'
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: run tests
          command: npm test